[package]
name = "rusmart-smt-stdlib"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>", "Mehrad Haghshenas <m3haghsh@uwaterloo.ca>"]
description = "Standard Rust library for SMT elements"
license = "GPL-3.0-or-later"
keywords = ["smt", "types", "modeling"]
categories = ["compilers"]
edition = "2024"
homepage = "https://github.com/meng-xu-cs/rusmart"
repository = "https://github.com/meng-xu-cs/rusmart.git"

[dependencies]
anyhow = { workspace = true }
internment = { workspace = true }
itertools = { workspace = true }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
paste = { workspace = true }
