[workspace]
members = [
    # ordered and grouped loosely by dependency relation
    "utils",
    "cli",
    "smt/stdlib",
    "smt/remark",
    "smt/remark/remark_derive",
    "smt/derive",
    "smt/testing_frontend",
    "smt/testing_backend",
    "lang/test",
    "lang/while",
    "lang/demo",
    "lang/rego",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
command-group = "5.0.1"
datatest-stable = "0.3.2"
internment = { version = "0.8.4", features = ["arc"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.27"
num_cpus = "1.16.0"
num-bigint = "0.4.6"
num-rational = "0.4.2"
num-traits = "0.2.19"
paste = "1"
petgraph = "0.8.1"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
tempfile = "3.20.0"
simplelog = "0.12.2"
walkdir = "2.5.0"
z3 = "0.12.0"

rusmart-utils = { path = "utils" }
rusmart-cli = { path = "cli" }
rusmart-smt-stdlib = { path = "smt/stdlib" }
rusmart-smt-remark = { path = "smt/remark" }
rusmart-smt-remark-derive = { path = "smt/remark/remark_derive" }
rusmart-smt-derive = { path = "smt/derive" }
rusmart-lang-test = { path = "lang/test" }