[workspace]
members = [
    "smt/stdlib",
    "smt/remark",
    "smt/remark/remark_derive",
    "smt/derive",
    "lang",
]
resolver = "2"

[workspace.package]
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/meng-xu-cs/rusmart"

[workspace.dependencies]
num_cpus = "1.17.0"
anyhow = "1.0.104"
command-group = "5.0.1"
log = "0.4.33"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full", "extra-traits"] }
tempfile = "3.27.0"
walkdir = "2.5.0"
bitvec = "1.1.1"
internment = "0.8.4"
itertools = "0.15.0"
num-bigint = "0.4.6"
num-rational = "0.4.2"
num-traits = "0.2.19"
paste = "1"
libm = "0.2.11"
ordered-float = "5.3.0"
clap = { version = "4.6.4", features = ["derive"] }
lazy_static = "1.5.0"

rusmt-smt-stdlib = { path = "smt/stdlib" }
rusmt-smt-remark = { path = "smt/remark" }
rusmt-smt-remark-derive = { path = "smt/remark/remark_derive" }
rusmt-lang = { path = "lang" }
