[workspace]
members = [
    "smt/stdlib",
    "smt/remark",
    "smt/remark/remark_derive",
    "smt/derive",
    "lang",
]
resolver = "2"

[workspace.dependencies]
datatest-stable = "0.3.3"
hexf-parse = "0.2.1"
num_cpus = "1.17.0"
anyhow = "1.0.102"
command-group = "5.0.1"
log = "0.4.29"
petgraph = "0.8.3"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full", "extra-traits"] }
tempfile = "3.27.0"
walkdir = "2.5.0"
bitvec = "1.0.1"
internment = { version = "0.8.4", features = ["arc"] }
itertools = "0.14.0"
num-bigint = "0.4.6"
num-rational = "0.4.2"
num-traits = "0.2.19"
paste = "1"
libm = "0.2.11"
ordered-float = "5.3.0"
clap = { version = "4.6.0", features = ["derive"] }

rusmart-smt-stdlib = { path = "smt/stdlib" }
rusmart-smt-remark = { path = "smt/remark" }
rusmart-smt-remark-derive = { path = "smt/remark/remark_derive" }
rusmart-smt-derive = { path = "smt/derive" }
