# Arrays can span multiple lines. A terminating comma (also called a trailing comma) is permitted after the last value of the array. 
# Any number of newlines and comments may precede values, commas, and the closing bracket. Indentation between array values and commas is treated as whitespace and ignored.


integers2 = [
  1, 2, 3
]

integers3 = [
  1,
  2, # this is ok




  #hello
]
