# case one - empty table (OK)
# [table]


## case two - table with values (OK)
# [table-1]
# key1 = "some string"
# key2 = 123

# [table-2]
# key1 = "another string"
# key2 = 456

# case three - quoted key parts (OK)
# [dog."tater.man"]
# type.name = "pug"

# case four - Whitespace around the key is ignored. (OK)
# [a.b.c]            # this is best practice
# [ d.e.f ]          # same as [d.e.f]
# [ g .  h  . i ]    # same as [g.h.i]
# [ j . "ʞ" . 'l' ]  # same as [j."ʞ".'l']

# case five - You don't need to specify all the super-tables if you don't want to (OK)
# [x] you
# [x.y] don't
# [x.y.z] need these
# [x.y.z.w] # for this to work

# [x] # defining a super-table afterward is ok

# case six - Like keys, you cannot define a table more than once. Doing so is invalid. (Error)
# [fruit]
# apple = "red"

# [fruit]
# orange = "orange"

# case seven - type mismatch error (Error)

# [fruit]
# apple = "red"

# [fruit.apple]
# texture = "smooth"

# case eight - Defining tables out-of-order is discouraged. (OK)
# [fruit.apple]
# [animal]
# [fruit.orange]

# case nine - The top-level table, also called the root table, starts at the beginning of the document and ends just before the first table header (or EOF). Unlike other tables, it is nameless and cannot be relocated.
# name = "Fido"
# breed = "pug"
# [owner]
# name = "Regina Dogman"
# member_since = 1999-08-04

# case ten - Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created. (OK)
# fruit.apple.color = "red"
# Defines a table named fruit
# Defines a table named fruit.apple

# fruit.apple.taste.sweet = true
# Defines a table named fruit.apple.taste
# fruit and fruit.apple were already created

# case eleven - Since tables cannot be defined more than once, redefining such tables using a [table] header is not allowed. Likewise, using dotted keys to redefine tables already defined in [table] form is not allowed. The [table] form can, however, be used to define sub-tables within tables defined via dotted keys. (Error)
# [fruit]
# apple.color = "red"
# apple.taste.sweet = true

# [fruit.apple]  # INVALID
# [fruit.apple.taste]  # INVALID

# [fruit.apple.texture]  # you can add sub-tables
# smooth = true

# case twelve - using dotted keys to redefine tables already defined in [table] form is not allowed. (Error)
[fruit.apple]

[fruit]
apple.color = "red"