#table1 = {} # Within the braces, zero or more comma-separated key/value pairs may appear. 
#animal = { type.name = "pug" }

# newline_inline_table = { key = "value",
# another_key= 42
# } # not permitted

# A terminating comma (also called trailing comma) is not permitted after the last key/value pair in an inline table.
#table123 = { key = "value" ,}  # not permitted

#[table]
#inline_table = { key = { another_key = 42 }, another_key= 42 }  # All value types are allowed, including inline tables.

#name = { first = "Tom", last = "Preston-Werner" }
#point = { x = 1, y = 2 }
#animal = { type.name = "pug" }