[package]
name = "rusmt-smt-remark"
version.workspace = true
description = "Constraint checking and code generation behind the #[smt_type] and #[smt_fn] attributes"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["smt", "annotation", "macros"]
categories = ["compilers", "development-tools::procedural-macro-helpers"]
edition.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
