[package]
name = "rusmart-smt-derive"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>", "Mehrad Haghshenas <m3haghsh@uwaterloo.ca>"]
description = "SMT model derivation from Rust code"
license = "GPL-3.0-or-later"
keywords = ["smt", "model", "derivation"]
categories = ["compilers", "parser-implementations"]
edition = "2024"
homepage = "https://github.com/meng-xu-cs/rusmart"
repository = "https://github.com/meng-xu-cs/rusmart.git"
 
[dependencies]
anyhow = { workspace = true }
command-group = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
tempfile = { workspace = true }
petgraph = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
walkdir = { workspace = true }
z3 = { workspace = true }
z3-sys = { workspace = true }

rusmart-utils = { workspace = true }