[package]
name = "rusmart-smt-remark-derive"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>", "Mehrad Haghshenas <m3haghsh@uwaterloo.ca>"]
description = "Annotations for remarking Rust syntax into SMT constructs"
license = "GPL-3.0-or-later"
keywords = ["smt", "annotation", "macros"]
categories = ["compilers"]
edition = "2024"
homepage = "https://github.com/meng-xu-cs/rusmart"
repository = "https://github.com/meng-xu-cs/rusmart.git"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }

rusmart-smt-remark = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }