[package]
name = "rusmart-lang"
description = "Declarative semantics for a Demo/Rego language for eval1 and eval2"
version = "0.1.0"
edition = "2021"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"

[dependencies]
anyhow = { workspace = true }
walkdir = {workspace = true}
rusmart-utils = { workspace = true }
rusmart-smt-stdlib = { workspace = true }
rusmart-smt-remark-derive = { workspace = true }
rusmart-smt-derive = { workspace = true }
