[package]
name = "rusmt-lang"
version = "0.1.0"
description = "Executable semantics of programming languages"
readme = "README.md"
repository = "https://github.com/meng-xu-cs/rusmart.git"
license = "GPL-3.0-or-later"
keywords = ["executable-semantics", "programming-languages", "functional-programming"]
categories = ["compilers", "parser-implementations"]
edition = "2024"

[dependencies]
rusmt-smt-stdlib = { workspace = true }
rusmt-smt-remark-derive = { workspace = true }
clap = { workspace = true }

[lints.clippy]
all = "allow"