[package]
name = "rusmt-lang"
version.workspace = true
description = "Executable semantics of programming languages"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["executable-semantics", "programming-languages", "functional-programming"]
categories = ["compilers", "parser-implementations"]
edition.workspace = true

[dependencies]
rusmt-smt-stdlib = { workspace = true }
rusmt-smt-remark-derive = { workspace = true }
clap = { workspace = true }

[lints.clippy]
all = "allow"

[dev-dependencies]
toml = "1.1.2"
