[package]
name = "rusmart-programs"
version = "0.1.0"
description = "Test programs for Rusmart SMT solver"
readme = "README.md"
repository = "https://github.com/meng-xu-cs/rusmart.git"
license = "GPL-3.0-or-later"
keywords = ["programs", "tests", "rusmart"]
categories = ["development-tools::testing"]
edition = "2024"

[dev-dependencies]
rusmart-smt-stdlib = { workspace = true }
rusmart-smt-remark-derive = { workspace = true }
rusmart-smt-derive = { workspace = true }
anyhow = {workspace = true}
datatest-stable = {workspace = true}

[lints.rust]
non_camel_case_types = "allow"
unused = "allow"

[lints.clippy]
all = "allow"

[[test]]
name = "integration"
harness = false