[book]
title = "Rusmart Framework"
authors = ["Meng Xu", "Mehrad Haghshenas"]
src = "src"
language = "en"
multilingual = false

[build]
create-missing = false

[rust]
edition = "2021"

[output.html.playground]
runnable = true